//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHero {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using UnityEngine;
    using Unity.Mathematics;
    using UnityEngine.Networking;
    using System.Text;
    
    
    [Serializable()]
    public class CameraCfg {
        
        [XmlAttribute("CameraName")]
        public string CameraName{ get; set; }//;
        
        [XmlAttribute("PosY")]
        public float PosY{ get; set; }//;
        
        [XmlAttribute("OffsetZ")]
        public float OffsetZ{ get; set; }//;
        
        [XmlAttribute("AssetPath")]
        public string AssetPath{ get; set; }//;
        
        [XmlAttribute("AssetName")]
        public string AssetName{ get; set; }//;
    }
    
    public struct CameraStruct {
        
        public string CameraName;
        
        public float PosY;
        
        public float OffsetZ;
        
        public string AssetPath;
        
        public string AssetName;
    }
    
    public sealed class CameraCfgMgr {
        
        private static SerializableDictionary<string, CameraCfg> cameraCfgDic;
        
        public static void Init() {
            var uri = new System.Uri(Path.Combine(Application.streamingAssetsPath, "xml","相机表.xml"));
            var request = UnityWebRequest.Get(uri.AbsoluteUri);
            request.SendWebRequest();
            while (!request.isDone){ if (request.isNetworkError) { Debug.Log(request.error); return;}};
            byte[] bytes = Encoding.UTF8.GetBytes(request.downloadHandler.text);
            MemoryStream stream = new MemoryStream();
            stream.Write(bytes, 0, bytes.Length);
            stream.Position = 0;
            XmlSerializer xmlFormatter = new XmlSerializer(typeof(SerializableDictionary<string, CameraCfg>));;
            cameraCfgDic = (SerializableDictionary<string, CameraCfg>)xmlFormatter.Deserialize(stream);;
            stream.Close();;
        }
        
        public static CameraCfg GetByCameraName(string cameraname) {
            if (!cameraCfgDic.TryGetValue(cameraname, out CameraCfg cfg)) {
              Debug.LogError("相机表: 配置表出错, 不存在id: "+cameraname );    
              return null;
            }
            return cfg;
        }
        
        public static List<CameraCfg> GetConfigList() {
            List<CameraCfg> list = new List<CameraCfg>();
            foreach (var item in cameraCfgDic){list.Add(item.Value);};
            return list;
        }
    }
}
