//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHero {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using UnityEngine;
    using Unity.Mathematics;
    using UnityEngine.Networking;
    using System.Text;
    
    
    [Serializable()]
    public class ItemCfg {
        
        [XmlAttribute("Id")]
        public int Id{ get; set; }//;
        
        [XmlAttribute("Name")]
        public string Name{ get; set; }//;
        
        [XmlAttribute("ResourceId")]
        public int ResourceId{ get; set; }//;
    }
    
    public struct ItemStruct {
        
        public int Id;
        
        public string Name;
        
        public int ResourceId;
    }
    
    public sealed class ItemCfgMgr {
        
        private static SerializableDictionary<int, ItemCfg> itemCfgDic;
        
        public static void Init() {
            var uri = new System.Uri(Path.Combine(Application.streamingAssetsPath, "xml","物品表.xml"));
            var request = UnityWebRequest.Get(uri.AbsoluteUri);
            request.SendWebRequest();
            while (!request.isDone){ if (request.isNetworkError) { Debug.Log(request.error); return;}};
            byte[] bytes = Encoding.UTF8.GetBytes(request.downloadHandler.text);
            MemoryStream stream = new MemoryStream();
            stream.Write(bytes, 0, bytes.Length);
            stream.Position = 0;
            XmlSerializer xmlFormatter = new XmlSerializer(typeof(SerializableDictionary<int, ItemCfg>));;
            itemCfgDic = (SerializableDictionary<int, ItemCfg>)xmlFormatter.Deserialize(stream);;
            stream.Close();;
        }
        
        public static ItemCfg GetById(int id) {
            if (!itemCfgDic.TryGetValue(id, out ItemCfg cfg)) {
              Debug.LogError("物品表: 配置表出错, 不存在id: "+id );    
              return null;
            }
            return cfg;
        }
        
        public static List<ItemCfg> GetConfigList() {
            List<ItemCfg> list = new List<ItemCfg>();
            foreach (var item in itemCfgDic){list.Add(item.Value);};
            return list;
        }
    }
}
