//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHero {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using UnityEngine;
    using Unity.Mathematics;
    using UnityEngine.Networking;
    using System.Text;
    
    
    [Serializable()]
    public class ResourceCfg {
        
        [XmlAttribute("Id")]
        public int Id{ get; set; }//;
        
        [XmlAttribute("AssetPath")]
        public string AssetPath{ get; set; }//;
        
        [XmlAttribute("AssetName")]
        public string AssetName{ get; set; }//;
    }
    
    public struct ResourceStruct {
        
        public int Id;
        
        public string AssetPath;
        
        public string AssetName;
    }
    
    public sealed class ResourceCfgMgr {
        
        private static SerializableDictionary<int, ResourceCfg> resourceCfgDic;
        
        public static void Init() {
            var uri = new System.Uri(Path.Combine(Application.streamingAssetsPath, "xml","资源映射表.xml"));
            var request = UnityWebRequest.Get(uri.AbsoluteUri);
            request.SendWebRequest();
            while (!request.isDone){ if (request.isNetworkError) { Debug.Log(request.error); return;}};
            byte[] bytes = Encoding.UTF8.GetBytes(request.downloadHandler.text);
            MemoryStream stream = new MemoryStream();
            stream.Write(bytes, 0, bytes.Length);
            stream.Position = 0;
            XmlSerializer xmlFormatter = new XmlSerializer(typeof(SerializableDictionary<int, ResourceCfg>));;
            resourceCfgDic = (SerializableDictionary<int, ResourceCfg>)xmlFormatter.Deserialize(stream);;
            stream.Close();;
        }
        
        public static ResourceCfg GetById(int id) {
            if (!resourceCfgDic.TryGetValue(id, out ResourceCfg cfg)) {
              Debug.LogError("资源映射表: 配置表出错, 不存在id: "+id );    
              return null;
            }
            return cfg;
        }
        
        public static List<ResourceCfg> GetConfigList() {
            List<ResourceCfg> list = new List<ResourceCfg>();
            foreach (var item in resourceCfgDic){list.Add(item.Value);};
            return list;
        }
    }
}
