//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHero {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using UnityEngine;
    using Unity.Mathematics;
    using UnityEngine.Networking;
    using System.Text;
    
    
    [Serializable()]
    public class SkillCfg {
        
        [XmlAttribute("SkillID")]
        public int SkillID{ get; set; }//;
        
        [XmlAttribute("Memo")]
        public string Memo{ get; set; }//;
        
        [XmlAttribute("CostEnergy")]
        public float CostEnergy{ get; set; }//;
        
        [XmlAttribute("CD")]
        public float CD{ get; set; }//;
        
        [XmlAttribute("AssetPath")]
        public string AssetPath{ get; set; }//;
        
        [XmlAttribute("AssetName")]
        public string AssetName{ get; set; }//;
    }
    
    public struct SkillStruct {
        
        public int SkillID;
        
        public string Memo;
        
        public float CostEnergy;
        
        public float CD;
        
        public string AssetPath;
        
        public string AssetName;
    }
    
    public sealed class SkillCfgMgr {
        
        private static SerializableDictionary<int, SkillCfg> skillCfgDic;
        
        public static void Init() {
            var uri = new System.Uri(Path.Combine(Application.streamingAssetsPath, "xml","技能表.xml"));
            var request = UnityWebRequest.Get(uri.AbsoluteUri);
            request.SendWebRequest();
            while (!request.isDone){ if (request.isNetworkError) { Debug.Log(request.error); return;}};
            byte[] bytes = Encoding.UTF8.GetBytes(request.downloadHandler.text);
            MemoryStream stream = new MemoryStream();
            stream.Write(bytes, 0, bytes.Length);
            stream.Position = 0;
            XmlSerializer xmlFormatter = new XmlSerializer(typeof(SerializableDictionary<int, SkillCfg>));;
            skillCfgDic = (SerializableDictionary<int, SkillCfg>)xmlFormatter.Deserialize(stream);;
            stream.Close();;
        }
        
        public static SkillCfg GetBySkillID(int skillid) {
            if (!skillCfgDic.TryGetValue(skillid, out SkillCfg cfg)) {
              Debug.LogError("技能表: 配置表出错, 不存在id: "+skillid );    
              return null;
            }
            return cfg;
        }
        
        public static List<SkillCfg> GetConfigList() {
            List<SkillCfg> list = new List<SkillCfg>();
            foreach (var item in skillCfgDic){list.Add(item.Value);};
            return list;
        }
    }
}
