//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHero {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using UnityEngine;
    using Unity.Mathematics;
    using UnityEngine.Networking;
    using System.Text;
    
    
    [Serializable()]
    public class CampCfg {
        
        [XmlAttribute("CampType")]
        public CampType CampType{ get; set; }//;
        
        [XmlAttribute("HealthBar")]
        public int HealthBar{ get; set; }//;
        
        [XmlAttribute("DieEffect")]
        public int DieEffect{ get; set; }//;
    }
    
    public struct CampStruct {
        
        public CampType CampType;
        
        public int HealthBar;
        
        public int DieEffect;
    }
    
    public sealed class CampCfgMgr {
        
        private static SerializableDictionary<CampType, CampCfg> campCfgDic;
        
        public static void Init() {
            var uri = new System.Uri(Path.Combine(Application.streamingAssetsPath, "xml","阵营表.xml"));
            var request = UnityWebRequest.Get(uri.AbsoluteUri);
            request.SendWebRequest();
            while (!request.isDone){ if (request.isNetworkError) { Debug.Log(request.error); return;}};
            byte[] bytes = Encoding.UTF8.GetBytes(request.downloadHandler.text);
            MemoryStream stream = new MemoryStream();
            stream.Write(bytes, 0, bytes.Length);
            stream.Position = 0;
            XmlSerializer xmlFormatter = new XmlSerializer(typeof(SerializableDictionary<CampType, CampCfg>));;
            campCfgDic = (SerializableDictionary<CampType, CampCfg>)xmlFormatter.Deserialize(stream);;
            stream.Close();;
        }
        
        public static CampCfg GetByCampType(CampType camptype) {
            if (!campCfgDic.TryGetValue(camptype, out CampCfg cfg)) {
              Debug.LogError("阵营表: 配置表出错, 不存在id: "+camptype );    
              return null;
            }
            return cfg;
        }
        
        public static List<CampCfg> GetConfigList() {
            List<CampCfg> list = new List<CampCfg>();
            foreach (var item in campCfgDic){list.Add(item.Value);};
            return list;
        }
    }
}
