//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHero {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using UnityEngine;
    using Unity.Mathematics;
    using UnityEngine.Networking;
    using System.Text;
    
    
    [Serializable()]
    public class GoldCostCfg {
        
        [XmlAttribute("Id")]
        public int Id{ get; set; }//;
        
        [XmlAttribute("CharacterType")]
        public CharacterType CharacterType{ get; set; }//;
        
        [XmlAttribute("Cost")]
        public int Cost{ get; set; }//;
    }
    
    public struct GoldCostStruct {
        
        public int Id;
        
        public CharacterType CharacterType;
        
        public int Cost;
    }
    
    public sealed class GoldCostCfgMgr {
        
        private static SerializableDictionary<int, GoldCostCfg> goldcostCfgDic;
        
        public static void Init() {
            var uri = new System.Uri(Path.Combine(Application.streamingAssetsPath, "xml","金币消耗表.xml"));
            var request = UnityWebRequest.Get(uri.AbsoluteUri);
            request.SendWebRequest();
            while (!request.isDone){ if (request.isNetworkError) { Debug.Log(request.error); return;}};
            byte[] bytes = Encoding.UTF8.GetBytes(request.downloadHandler.text);
            MemoryStream stream = new MemoryStream();
            stream.Write(bytes, 0, bytes.Length);
            stream.Position = 0;
            XmlSerializer xmlFormatter = new XmlSerializer(typeof(SerializableDictionary<int, GoldCostCfg>));;
            goldcostCfgDic = (SerializableDictionary<int, GoldCostCfg>)xmlFormatter.Deserialize(stream);;
            stream.Close();;
        }
        
        public static GoldCostCfg GetById(int id) {
            if (!goldcostCfgDic.TryGetValue(id, out GoldCostCfg cfg)) {
              Debug.LogError("金币消耗表: 配置表出错, 不存在id: "+id );    
              return null;
            }
            return cfg;
        }
        
        public static List<GoldCostCfg> GetConfigList() {
            List<GoldCostCfg> list = new List<GoldCostCfg>();
            foreach (var item in goldcostCfgDic){list.Add(item.Value);};
            return list;
        }
    }
}
