//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHero {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using UnityEngine;
    using Unity.Mathematics;
    using UnityEngine.Networking;
    using System.Text;
    
    
    [Serializable()]
    public class IconCfg {
        
        [XmlAttribute("Id")]
        public int Id{ get; set; }//;
        
        [XmlAttribute("AssetPath")]
        public string AssetPath{ get; set; }//;
        
        [XmlAttribute("AtlasName")]
        public string AtlasName{ get; set; }//;
        
        [XmlAttribute("SpriteName")]
        public string SpriteName{ get; set; }//;
    }
    
    public struct IconStruct {
        
        public int Id;
        
        public string AssetPath;
        
        public string AtlasName;
        
        public string SpriteName;
    }
    
    public sealed class IconCfgMgr {
        
        private static SerializableDictionary<int, IconCfg> iconCfgDic;
        
        public static void Init() {
            var uri = new System.Uri(Path.Combine(Application.streamingAssetsPath, "xml","图标表.xml"));
            var request = UnityWebRequest.Get(uri.AbsoluteUri);
            request.SendWebRequest();
            while (!request.isDone){ if (request.isNetworkError) { Debug.Log(request.error); return;}};
            byte[] bytes = Encoding.UTF8.GetBytes(request.downloadHandler.text);
            MemoryStream stream = new MemoryStream();
            stream.Write(bytes, 0, bytes.Length);
            stream.Position = 0;
            XmlSerializer xmlFormatter = new XmlSerializer(typeof(SerializableDictionary<int, IconCfg>));;
            iconCfgDic = (SerializableDictionary<int, IconCfg>)xmlFormatter.Deserialize(stream);;
            stream.Close();;
        }
        
        public static IconCfg GetById(int id) {
            if (!iconCfgDic.TryGetValue(id, out IconCfg cfg)) {
              Debug.LogError("图标表: 配置表出错, 不存在id: "+id );    
              return null;
            }
            return cfg;
        }
        
        public static List<IconCfg> GetConfigList() {
            List<IconCfg> list = new List<IconCfg>();
            foreach (var item in iconCfgDic){list.Add(item.Value);};
            return list;
        }
    }
}
