//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHero {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using UnityEngine;
    using Unity.Mathematics;
    using UnityEngine.Networking;
    using System.Text;
    
    
    [Serializable()]
    public class LevelCfg {
        
        [XmlAttribute("Level")]
        public int Level{ get; set; }//;
        
        [XmlAttribute("Exp")]
        public float Exp{ get; set; }//;
    }
    
    public struct LevelStruct {
        
        public int Level;
        
        public float Exp;
    }
    
    public sealed class LevelCfgMgr {
        
        private static SerializableDictionary<int, LevelCfg> levelCfgDic;
        
        public static void Init() {
            var uri = new System.Uri(Path.Combine(Application.streamingAssetsPath, "xml","经验等级表.xml"));
            var request = UnityWebRequest.Get(uri.AbsoluteUri);
            request.SendWebRequest();
            while (!request.isDone){ if (request.isNetworkError) { Debug.Log(request.error); return;}};
            byte[] bytes = Encoding.UTF8.GetBytes(request.downloadHandler.text);
            MemoryStream stream = new MemoryStream();
            stream.Write(bytes, 0, bytes.Length);
            stream.Position = 0;
            XmlSerializer xmlFormatter = new XmlSerializer(typeof(SerializableDictionary<int, LevelCfg>));;
            levelCfgDic = (SerializableDictionary<int, LevelCfg>)xmlFormatter.Deserialize(stream);;
            stream.Close();;
        }
        
        public static LevelCfg GetByLevel(int level) {
            if (!levelCfgDic.TryGetValue(level, out LevelCfg cfg)) {
              Debug.LogError("经验等级表: 配置表出错, 不存在id: "+level );    
              return null;
            }
            return cfg;
        }
        
        public static List<LevelCfg> GetConfigList() {
            List<LevelCfg> list = new List<LevelCfg>();
            foreach (var item in levelCfgDic){list.Add(item.Value);};
            return list;
        }
    }
}
